version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hotel-postgres
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hotel-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: hotel-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hotel.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - hotel-network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  hotel-network:
    driver: bridge